#!/bin/bash

# Run checks
# Linting is done on a per-environment basis, due to the differing values that exist.
./gradlew \
  detekt \
  ktlintCheck \
  lintDebug \
  testDebugUnitTest \
  vale \
  --daemon
